services:
  backend:
    build: ./backend
    container_name: devsecurity
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  devsecurity-frontend:
    build: ./devsecurity-frontend
    container_name: devsecurity-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
