FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt .
COPY ./entrypoint.sh .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY backend/ .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN chmod +x /app/entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "sh", "entrypoint.sh" ]
